config/routes.rb
Devilmaster::Application.routes.draw do
  resources :players
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',                          to: 'players#new'
  match '/signin',                          to: 'sessions#new'
  match '/signout',                         to: 'sessions#destroy', via: :delete
  match '/start',                           to: 'game#start'
  match '/main',                            to: 'game#main'
  match '/level_up',                        to: 'game#level_up'
  match '/card_get',                        to: 'game#card_get'
  match '/battle_select_opponent',          to: 'battle#select_opponent'
  match '/battle_select_opponent_bylevel',  to: 'battle#select_opponent_bylevel'
  match '/battle_select_card',              to: 'battle#select_card'
  match '/battle_execute',                  to: 'battle#execute'
  match '/battle_result',                   to: 'battle#result'

  root to: 'sessions#new'

end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  strength   :integer
#  image      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Card < ActiveRecord::Base
  attr_accessible :name, :strength, :image
  has_many :player_cards
  has_many :players, :through => :player_cards
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  tribe      :string(255)
#  level      :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Player < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :tribe, :level
  has_secure_password
  before_save :create_remember_token

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,      presence:     true,
                        length:       { maximum: 50 }
  validates :email,     presence:     true,
                        format:       { with: email_regex },
                        uniqueness:   { case_sensitive: false } 
  validates :password,  presence:     true,
                        confirmation: true,
                        length:       { minimum: 6 }

  private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
  has_many :player_cards
  has_many :cards, :through => :player_cards
end

app/models/player_card.rb
class PlayerCard < ActiveRecord::Base
  belongs_to :player
  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/battle_controller.rb
class BattleController < ApplicationController
  include BattleHelper
  before_filter :set_state

  def set_state
    @player = current_player
    unless session[:opponent_id].blank?
      @opponent = Player.find(session[:opponent_id])
    end
    unless session[:player_card_id].blank?
      @player_card = Card.find(session[:player_card_id])
    end
    unless session[:opponent_card_id].blank?
      @opponent_card = Card.find(session[:opponent_card_id])
    end
  end

  def select_opponent
    @player = current_player 
  end

  def select_opponent_bylevel
    @players = Player.all
  end

  def select_card
    session[:opponent_id] = params[:opponent_id]
    set_state
    @cards = @player.cards
  end 

  def execute 
    session[:player_card_id] = params[:card_id]
    session[:opponent_card_id] = 2 
    set_state
 end

  def result
    if @player_card.strength > @opponent_card.strength 
      @result = "win"
    else
      @result = "lose"
    end
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_filter :set_state

  def set_state
    @player = current_player
  end

  def start
  end

  def main
    if @player.level.nil?
      @player.update_attributes(level: 1)
      @player_card = PlayerCard.new
      @player_card.update_attributes(player_id: @player.id, card_id: 1)
      @player_card = PlayerCard.new
      @player_card.update_attributes(player_id: @player.id, card_id: 2)
      @player_card = PlayerCard.new
      @player_card.update_attributes(player_id: @player.id, card_id: 3)
      @player_card = PlayerCard.new
      @player_card.update_attributes(player_id: @player.id, card_id: 4)
      #redirect_to level_up_path level: 1 
    end
  end

  def level_up
  end

  def card_get
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :signed_in_player, only: [:index, :edit, :update]
  before_filter :correct_player,   only: [:edit, :update]
  before_filter :admin_user,       only: :destroy

  def index 
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
    @title = "Sign Up"
  end

  def create
    @player = Player.new(params[:player])
    if @player.save
      sign_in @player
      redirect_to main_path 
    else
      @title = "Sign Up"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @player.update_attributes(params[:player])
      sign_in @player
      redirect_to @player
    else
      render 'edit'
    end
  end

  def destroy
    Player.find(params[:id]).destroy
    redirect_to players_path
  end

  private

  def signed_in_player
    redirect_to signin_path, notice: "Please sign in." unless signed_in?
  end

  def correct_player
    @player = Player.find(params[:id])
    redirect_to(root_path) unless current_player?(@player)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
 
  def create
    player = Player.find_by_email(params[:session][:email])
    if player && player.authenticate(params[:session][:password])
      sign_in player
      redirect_to main_path 
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to signin_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battle_helper.rb
module BattleHelper
  def current_opponent=(player)
    @current_opponent = player
  end

  def current_opponent
    @current_opponent
  end

  def current_player_card=(card)
    @player_card = card
  end

  def current_opponent_card=(card)
    @opponent_card = card
  end

  def result=(result)
    @result = result
  end
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(player)
    cookies.permanent[:remember_token] = player.remember_token
    current_player = player
  end

  def signed_in?
    !current_player.nil?
  end

  def current_player=(player)
    @current_player = player
  end

  def current_player
    @current_player ||= player_from_remember_token
  end

  def current_player?(player)
    player == current_player
  end

  def sign_out
    cookies.delete(:remember_token)
  end

  private

  def player_from_remember_token
    remember_token = cookies[:remember_token]
    Player.find_by_remember_token(remember_token) unless remember_token.nil?
  end
end

app/views/battle/execute.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "jquery.animate-enhanced.js" %>
  <%= javascript_include_tag "animate.js" %>
<% end %>

<div data-role="header">
  <h1>バトル</h1>
  <%= link_to "進む", battle_result_path,
    {"data-icon" => "arrow-r", "data-transition" => "slide", "class" => "ui-btn-right"}
  %>
</div>

<br>
<div id="img_l", style="position:relative", align="center">
  <%= image_tag(@player_card.image) %>
</div>
<div id="text", style="position:relative", align="center">
  <b>対<b>
</div>
<div id="img_r", style="position:relative", align="center">
  <%= image_tag(@opponent_card.image) %>
</div>

app/views/battle/result.html.erb
<div data-role="header" data-position="inline">
  <h1>バトル結果</h1>
  <%=
    link_to "完了", main_path,
    {"data-icon" => "check", "data-transition" => "slide", "class" => "ui-btn-right"}
   %>
</div>

<div style="position:relative", align="center">
  <br>
  <%= image_tag(@player_card.image) %>
</div>
<br>
<div style="text-align:center">
  <big><b>
    <% if @result == "win" %>
      勝利！
    <% else %>
      負け！
    <% end %>
    </b><big>
</div>

app/views/battle/select_card.html.erb
<div data-role="header">
  <h1>カードを選ぶ</h1>
</div>

<ul data-role="listview" data-theme="c">
  <% @cards.each do |card| %>
    <li>
    <%= link_to raw("#{image_tag(card.image)}<h3>#{card.name}</h3>"),
      battle_execute_path(:card_id => card.id)
    %>
    </li>
  <% end %>
</ul>

app/views/battle/select_opponent.html.erb
<div data-role="header">
  <h1>バトル相手選択</h1>
</div>

<div data-role="controlgroup">
  <%= link_to "エンブレムから選ぶ", "#",
    {"data-role" => "button", "data-transition" => "slide"}
  %>
  <%= link_to "レベルから選ぶ", battle_select_opponent_bylevel_path,
    {"data-role" => "button", "data-transition" => "slide"}
  %>
  <%= link_to "リベンジバトル", "#",
    {"data-role" => "button", "data-transition" => "slide"}
  %>
</div>

app/views/battle/select_opponent_bylevel.html.erb
<div data-role="header">
  <h1>レベルから選ぶ</h1>
</div>

<ul data-role="listview" data-theme="c">
  <% @players.each do |player| %>
    <li>
    <%= link_to player.name, battle_select_card_path(:opponent_id => player.id) %>
    </li>
  <% end %>
</ul>

app/views/game/card_get.html.erb
<div align="center">
  <%= link_to "戻る", main_path, {"data-role" => "button", "data-inline" => "true", "data-transition" => "slide"} %>
</div>

app/views/game/level_up.html.erb
<div align="center">
  <%= link_to "戻る", main_path, {"data-role" => "button", "data-inline" => "true", "data-transition" => "slide"} %>
</div>
<%= @player.level %>

app/views/game/main.html.erb
<div data-role="header">
  <%= link_to "ログアウト", signout_path, 
    {method: :delete, "data-icon" => "arrow-l", "data-transition" => "slide", "class" => "ui-btn-left"}
  %>
  <h1>メイン画面</h1>
</div>
<div align="center">
名前：<%= @player.name %>
<br>
レベル：<%= @player.level %>
</div>
<div data-role="controlgroup">
  <%= link_to "バトルを開始", battle_select_opponent_path,
    {"data-role" => "button", "data-transition" => "slide"}
  %>
  <%= link_to "クエストを開始", "#",
    {"data-role" => "button", "data-transition" => "slide"}
  %>
</div>

app/views/game/start.html.erb
<br><br><br><br>
<div align="center">
  デビルマスター（仮）
</div>

<div align="center">
  <%= link_to "スタート", main_path, {"data-role" => "button", "data-inline" => "true", "data-transition" => "slide"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <%= yield :meta_includes %>
  <head>
    <title>デビルマスター</title>
    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.css" %>
    <%= yield :style_includes %>
    <%= javascript_include_tag "jquery.js" %>
    <%= javascript_include_tag "jquery_ujs.js" %>
    <%= javascript_include_tag "http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.js" %>
    <%= yield :javascript_includes %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div data-role="page">
      <%= yield %>
    </div>
  </body>
</html>

app/views/players/_player.html.erb
<li>
  <%= link_to player.name, player %>
  <% if current_player.admin? && !current_player?(player) %>
    | <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
  <% end %>
</li>

app/views/players/edit.html.erb
<div data-role="header">
  <h1>プレイヤー情報を更新する</h1>
</div>

<%= form_for(@player) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name, "名前" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, "メール" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "パスワード確認" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "更新" %>
  </div>
<% end %>

app/views/players/index.html.erb
<div data-role="header">
  <h1>全プレイヤー</h1>
</div>

<ul class="players">
  <% @players.each do |player| %>
    <%= player.name %>
  <% end %>
</ul>

app/views/players/new.html.erb
<h1>Players#new</h1>
<p>Find me in app/views/players/new.html.erb</p>

app/views/players/show.html.erb
<%= @player.name %>, <%= @player.tribe %>, <%= @player.level %>

app/views/shared/_error_messages.html.erb
<% if @player.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@player.errors.count, "error") %> 
        prohibited this player from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>